name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal ./tests/JustSaying.UnitTests/JustSaying.UnitTests.csproj
        dotnet test --no-build --verbosity normal ./tests/JustSaying.Extensions.DependencyInjection.StructureMap.Tests/JustSaying.Extensions.DependencyInjection.StructureMap.Tests.csproj
    - name: Integration Test
      run: |
        goaws_tag=latest
        docker pull pafortin/goaws:$goaws_tag
        docker run -d --name goaws -p 4100:4100 pafortin/goaws:$goaws_tag
        export AWS_SERVICE_URL="http://localhost:4100"
        dotnet test --no-build --verbosity normal ./tests/JustSaying.IntegrationTests/JustSaying.IntegrationTests.csproj
